FROM python:3.9-alpine
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip

WORKDIR /pagina_qr
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD python manage.py runserver 0.0.0.0:80